### ISSUE TITLE
Design Depth Scroller Page

### ISSUE THREAD

**Issue by CodeFusion** [nomycao/Cruise_Ship#5]
Mockup of fish depth page

**Comment by ZIPXIII** [comment]
make the web page as Atlantic Ocean with the Depth Rule on the left,  arrange the different sea-creatures base on the OTN DATA, by scrolling the web-page to  to the information, then move your mouse to show the names of the sea-creature and click in to show more information, some of the fish with recipe pin can link to Recipe Page~

**Comment by ZIPXIII** [comment]
## I'll pose more resource about this web site
