### ISSUE TITLE
Mockup of Satellite Map

### ISSUE THREAD

**Issue by CodeFusion** [nomycao/Cruise_Ship#6]
Map overview and fish pathing

**Comment by Rzhou9** [comment]
showing a map of the ocean around halifax. And highlight different areas by colors with directly real fish image and number. It use visual date to educate people different fishes live in different areas, and also the number shows the deep of this fish like to live.

**Comment by nomycao** [comment]
we want to show where the different fishes are and where are our cruise lines. And we represent them to our visitors.
