### ISSUE TITLE
Mockup of fish consumption page

### ISSUE THREAD

**Issue by CodeFusion** [nomycao/Cruise_Ship#7]
Fish flavour and cooking page

**Comment by nomycao** [comment]
The different kinds of dishes

**Comment by Rzhou9** [comment]
Showing all kinds of fish dish images firstly on this menu page to guide consumer clicking it.
After getting in each image page, there are recipe and some data, such as size, deep, season, age, weight,  about the fish of this dish. It is information expression, and also a kind of education part.
